CREATE TABLE ROBOT_DATA
(
    id INTEGER NOT NULL,
    xpos VARCHAR(255) NOT NULL,
    ypos VARCHAR(255) NOT NULL,
    orientation VARCHAR(255) NOT NULL,
    depth VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE ROBOT_DEPTH_DATA
(
    id IDENTITY NOT NULL PRIMARY KEY,
    depth VARCHAR(255) NOT NULL
);

CREATE TABLE ROBOT_IMAGE_DATA
(
    id IDENTITY NOT NULL PRIMARY KEY,
    xpos VARCHAR(255) NOT NULL,
    ypos VARCHAR(255) NOT NULL,
    depth VARCHAR(255) NOT NULL
);